for (var KEY in OBJECT){ OPERATION } 
for (var KEY, VALUE in OBJECT){ OPERATION }

for (KEY in OBJECT){ OPERATION } 
for (KEY, VALUE in OBJECT){ OPERATION }

for (var KEY, VALUE in OBJECT) OPERATION;
for (KEY, VALUE in OBJECT) OPERATION;

for (var KEY in OBJECT){ var VALUE = OBJECT [KEY] } 

for (var KEY, VALUE in COMPLEX_OBJECT.TEST){ OPERATION }
for (var KEY, VALUE in COMPLEX_OBJECT ()){ OPERATION }